### ISSUE TITLE
CSS Pre/Post Processors for "Internal" Use

### ISSUE THREAD

**Issue by kitsonk** [dojo/meta#30]
Dojo 1 used less as a pre-processor, but largely the team has felt that wasn't the best decision and subsequent development has focused on [Stylus](http://stylus-lang.com/).

[SASS](http://sass-lang.com/) is very popular as a CSS pre-processor, but being based on Ruby increases the dependencies on what is largely a design-goal of having JavaScript based tooling for Dojo 2.  There would have to be a compelling reason (in my opinion) to adopt SASS.

In addition, with a desire to utilise FlexBox for layout with Dojo 2 widgets, there maybe a need for either using a post-processor or a some sort mixin solution (e.g. [nib](http://nibstyl.us/) for Stylus) for the pre-processor to be able to transform the CSS.

We also need how a pre-processor would work along side any sort of CSS modularity solutions (see #28).

**Comment by dylans** [comment]
fwiw, SASS no longer requires Ruby, as there's a Node.js version of it now that stays in sync with the Ruby version.

At a minimum, it's worth a re-evaluation of SASS as it's become far more robust since our last major evaluation two years ago.

**Comment by kitsonk** [comment]
Agreed.  We should take a look at SASS again given that.  I know looking for the ability to "shim" FlexBox support, there were solutions that allowed easy processing with SASS.  I suspect users of Dojo 2 would find it easier to integrate into their projects if we standardised on SASS.  My only reservation was about the Ruby.

**Comment by mwistrand** [comment]
At this point I have used LESS, Stylus, and Sass for managing styles on large production apps, and agree that LESS is inferior to both Stylus and Sass. Between Sass and Stylus, I personally have enjoyed using Stylus more, as it feels more like how a JS developer would write CSS (but of course, that is incredibly subjective). Doing as thorough a feature comparison as possible in a reasonable amount of time, Sass provides the same functionality as Stylus, with few execptions (e.g., an introspection API or native Node middleware support). So it could feasibly be used as the default preprocessor for Dojo 2 components. As @dylans has already mentioned, Sass no longer requires Ruby, and we could use the [grunt-sass](https://github.com/sindresorhus/grunt-sass) task by Sindre Sorhus for compiling Sass to CSS.

Fortunately, both Sass and Stylus place nicely with [CSS Modules](https://github.com/css-modules/css-modules), (assumming  that is [what we decide to use for CSS modularity](https://github.com/dojo/meta/issues/28#issuecomment-219558811)). That said, in order to reap the benefits of local selectors and composability, we would need to avoid using the `@import` or `@extend` functionality provided by the preprocessor, instead relying solely on `composes`:

```css
.common {
  // base component styles go here.
}
.variation {
  composes: common;
}
.otherVariation {
  composes: common;
  
  // The CSS Modules specification includes the ".css" extension on imports,
  // but it feels odd to me to write to one file type, but import another.
  // In my opinion, it would instead be ideal if the loader plugin could
  // assume the ".css" extension.
  composes: variation from './OtherComponent';
}
```

Both Sass and Stylus leave the `composes` properties as-is:

```css
.common {}
.variation { composes: common; }
.otherVariation {
  composes: common;
  composes: variation from './OtherComponent';
}
```

They also preserve the `:global` and `:local` flags:

```css
:global {
  .first {}
  .second {}
}
:global(.third) {}
```

Becomes:

```css
:global .first {}
:global .second {}
:global(.third) {}
```

Once the appropriate Grunt task has operated on the `.styl` or `.scss` files, the result could be passed onto any other tasks to ensure the CSS Modules-compatible CSS is further converted to the final format.
