### ISSUE TITLE
Change all travis.yml to only send slack notifications for failed builds

### ISSUE THREAD

**Issue by rishson** [dojo/meta#69]
Wondering why we have slack notifications into dojo2 for every successful build? Its getting spammy.

**Comment by kitsonk** [comment]
Mostly because it wasn't so spammy and cool when we started it...

It would seem [change](https://docs.travis-ci.com/user/notifications/#Notifications) is a more appropriate level of notification:

```yml
notifications:
  slack:
    on_success: change
```

**Comment by kitsonk** [comment]
Also, the `codecov.yml` can be changed, so it only posts if the coverage changes by ±2%:

```yml
coverage:
  notify:
    slack:
      default:
        url: ""
        threshold: 2
        attachments: "sunburst, diff"
```
